$schema: "https://github.com/lastmile-ai/mcp-agent/blob/main/schema/mcp-agent.config.schema.json"

execution_engine: asyncio
logger:
  type: file
  level: info
  transports: ["console", "file"]
  path: "mcp-agent.log"
  progress_display: true
  show_progress: true


mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    webSearch:
      command: "D:/GitRepo/rag-mcp-agent/.venv/Scripts/python.exe"
      args: ["D:/GitRepo/rag-mcp-agent/Servers/BraveSearch.py"]
      # transport: streamable_http
      # url: http://127.0.0.1:8888/mcp
    ragSearch:
      command: "D:/GitRepo/rag-mcp-agent/.venv/Scripts/python.exe"
      args: ["D:/GitRepo/rag-mcp-agent/Servers/RAGSearch.py"]

openai:
  # 将 API 调整为阿里云百炼大模型平台的 OpenAI 兼容 API
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  # 模型选用 qwen-turbo
  default_model: "qwen-turbo"
